import { supabase } from "@/integrations/supabase/client";
import type { MockUser } from "@/modules/admin/types/user.types";
import type { MockCoupon } from "@/modules/admin/types/coupon.types";
import type { IntegrationStatus } from "@/modules/admin/types/integration.types";
const table=supabase.from as unknown as (name:string)=>any;
const day=(v:string)=>new Intl.DateTimeFormat('pt-BR').format(new Date(v));
const ago=(v:string)=>{const h=Math.floor((Date.now()-Date.parse(v))/3600000);return h<1?'agora':h<24?`ha ${h}h`:`ha ${Math.floor(h/24)} dias`;};
const orders=async()=>{const all:any[]=[];for(const name of ['course_orders','beat_orders','digital_product_orders']){const {data,error}=await table(name).select('id,status,amount_cents,created_at,paid_at').order('created_at',{ascending:false}).limit(500);if(error)throw new Error(error.message);all.push(...(data??[]));}return all;};
export const adminService={
 async getDashboardStats(){const {count:users,error}=await table('user_profiles').select('id',{count:'exact',head:true});if(error)throw new Error(error.message);const all=await orders();const paid=all.filter(x=>['paid','completed'].includes(String(x.status)));const since=Date.now()-30*86400000;const recent=paid.filter(x=>Date.parse(x.paid_at??x.created_at)>=since);return{activeUsers:users??0,activeUsersDeltaPct:0,salesLast30Days:recent.reduce((s,x)=>s+(x.amount_cents??0),0),salesDeltaPct:0,orders:recent.length,ordersDeltaPct:0,conversionRatePct:all.length?Number((paid.length/all.length*100).toFixed(2)):0,conversionDeltaPct:0};},
 async getSalesSeries(){const all=(await orders()).filter(x=>['paid','completed'].includes(String(x.status)));const map=new Map<string,number>();all.forEach(x=>{const d=day(x.paid_at??x.created_at);map.set(d,(map.get(d)??0)+(x.amount_cents??0));});return[...map].slice(-30).map(([date,sales])=>({date,sales}));},
 async getStudentsSeries(){const {data,error}=await table('user_profiles').select('created_at').eq('role','student').order('created_at');if(error)throw new Error(error.message);let n=0;return(data??[]).map((x:any)=>({date:day(x.created_at),students:++n})).slice(-30);},
 async getTopProducts(){const {data,error}=await table('seller_products').select('title,digital_product_order_items(id)').limit(10);if(error)throw new Error(error.message);return(data??[]).map((x:any,i:number)=>({rank:i+1,title:x.title,sales:x.digital_product_order_items?.length??0})).sort((a:any,b:any)=>b.sales-a.sales);},
 async getRecentSales(){const all=(await orders()).filter(x=>['paid','completed'].includes(String(x.status))).sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at)).slice(0,10);return all.map(x=>({customer:String(x.id).slice(0,8),item:'Pedido da plataforma',amountCents:x.amount_cents??0,time:ago(x.created_at)}));},
 async getAlerts(){const {count}=await table('support_tickets').select('id',{count:'exact',head:true}).eq('status','open');return count?[{title:`${count} tickets de suporte abertos`,severity:'alta' as const}]:[];},
 async getRecentActivity(){const logs=await this.listAuditLogs();return logs.slice(0,10).map(x=>({actor:x.user,action:x.action,time:x.date}));},
 async getUpcomingEvents(){const {data,error}=await table('events').select('title,starts_at,registration_count').in('status',['upcoming','live']).order('starts_at').limit(10);if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({title:x.title,date:day(x.starts_at),attendees:x.registration_count}));},
 async listUsers():Promise<MockUser[]>{const {data,error}=await table('user_profiles').select('user_id,full_name,role,created_at').order('created_at',{ascending:false});if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({name:x.full_name??'Usuario',email:`${String(x.user_id).slice(0,8)}@id.local`,role:x.role,status:'Ativo',subscriptionPlan:'Gratuito',joinedAt:day(x.created_at)}));},
 async listStudents(){return(await this.listUsers()).filter(x=>x.role==='student');},
 async listCoupons():Promise<MockCoupon[]>{const {data,error}=await table('discount_coupons').select('code,discount_type,discount_value,ends_at,usage_limit,active,coupon_redemptions(id)').order('created_at',{ascending:false});if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({code:x.code,discountLabel:x.discount_type==='percentage'?`${x.discount_value}%`:`R$ ${(x.discount_value/100).toFixed(2)}`,validUntil:x.ends_at?day(x.ends_at):'Sem prazo',maxUses:x.usage_limit??0,used:x.coupon_redemptions?.length??0,status:x.active&&(!x.ends_at||Date.parse(x.ends_at)>Date.now())?'ativo':'expirado'}));},
 async listIntegrations():Promise<IntegrationStatus[]>{const {data,error}=await table('platform_integrations').select('display_name,category,status').order('display_name');if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({name:x.display_name,description:x.category,status:x.status==='connected'?'conectado':'desconectado'}));},
 async toggleIntegration(name:string){const {data:user}=await supabase.auth.getUser();const {data,error}=await table('platform_integrations').select('key,status').eq('display_name',name).single();if(error)throw new Error(error.message);const {error:updateError}=await table('platform_integrations').update({status:data.status==='connected'?'disconnected':'connected',updated_by:user.user?.id}).eq('key',data.key);if(updateError)throw new Error(updateError.message);return{success:true as const};},
 async getFinanceSummary(){const all=await orders();const paid=all.filter(x=>['paid','completed'].includes(String(x.status)));return{balanceCents:paid.reduce((s,x)=>s+(x.amount_cents??0),0),pendingPayoutCents:0,nextPayoutDate:'Nao agendado',taxesDueCents:0};},
 async listTransactions(){const {data,error}=await table('ledger_transactions').select('id,description,event_type,occurred_at,ledger_entries(amount_cents)').order('occurred_at',{ascending:false}).limit(100);if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({id:String(x.id).slice(0,8),description:x.description,amountCents:(x.ledger_entries??[]).reduce((s:number,e:any)=>s+(e.amount_cents??0),0),type:x.event_type==='payout'?'saida' as const:'entrada' as const,date:day(x.occurred_at)}));},
 async listInvoices(){return[];},
 async listCampaigns(){const {data,error}=await table('marketing_campaigns').select('name,channel,status').order('created_at',{ascending:false});if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({name:x.name,channel:x.channel,status:x.status==='active'?'ativa' as const:'agendada' as const,leads:0,conversionPct:0}));},
 async listLeads(){const {data,error}=await table('marketing_leads').select('name,email,source,created_at').order('created_at',{ascending:false});if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({name:x.name??'Lead',email:x.email,source:x.source,createdAt:day(x.created_at)}));},
 async listLandingPages(){const {data,error}=await table('cms_documents').select('title,status').eq('document_type','landing_page').order('created_at',{ascending:false});if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({name:x.title,visits:0,conversionPct:0,status:x.status==='published'?'publicada' as const:'rascunho' as const}));},
 async listAuditLogs(){const {data,error}=await table('admin_audit_logs').select('actor_name_snapshot,action,entity_type,created_at').order('created_at',{ascending:false}).limit(200);if(error)throw new Error(error.message);return(data??[]).map((x:any)=>({user:x.actor_name_snapshot,action:`${x.action} · ${x.entity_type}`,date:day(x.created_at),severity:'info' as const}));},
 async listAccessSessions(){return[];},
 async listRoles(){return[{role:'student',description:'Area do aluno'},{role:'producer',description:'Produtos e beats'},{role:'instructor',description:'Cursos e alunos'},{role:'admin',description:'Painel administrativo'},{role:'super_admin',description:'Administracao e seguranca'}];},
 async revokeSession(_sessionId?: string){throw new Error('Revogacao remota de sessoes sera ativada na etapa de APIs administrativas.');},
 async getSubscriptionSummary(){return{activeSubscribers:0,mrrCents:0,churnRatePct:0,trialUsers:0};},async listSubscriptionPlans(){return[];},async listSubscriptions(){return[];}
};
