export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/matricule-se',
  forgotPassword: '/esqueceu-senha',
  resetPassword: '/redefinir-senha',
  verifyEmail: '/verificar-email',
  verified: '/verificado',
  comingSoon: '/curso-em-breve',
  accessDenied: '/acesso-negado',
  contact: '/contato',
  paymentSuccess: '/pagamento-sucesso',
  validateCertificate: '/validar',

  // Public — Academy / Marketplace / Checkout
  academy: '/academia',
  academyCourse: (courseSlug: string) => `/academia/${courseSlug}`,
  academyLesson: (courseSlug: string, lessonSlug: string) => `/academia/${courseSlug}/aulas/${lessonSlug}`,
  lesson: (lessonId: string) => `/aula/${lessonId}`,
  marketplace: '/marketplace',
  marketplaceProduct: (productSlug: string) => `/marketplace/${productSlug}`,
  marketplaceBeats: '/marketplace/beats',
  marketplaceBeat: (beatSlug: string) => `/marketplace/beats/${beatSlug}`,
  cart: '/carrinho',
  checkout: '/checkout',

  // Public — content/community/events/VIP
  vipArea: '/area-vip',
  premiumLibraryPublic: '/biblioteca-premium',
  contentPortal: '/conteudos',
  contentArticle: (articleSlug: string) => `/conteudos/${articleSlug}`,
  eventsPublic: '/eventos',
  eventDetail: (eventSlug: string) => `/eventos/${eventSlug}`,
  communityPublic: '/comunidade',
  opportunitiesPublic: '/oportunidades',

  // Student area — /aluno/*
  dashboard: '/aluno',
  myCourses: '/aluno/meus-cursos',
  studentCourse: (courseId: string) => `/aluno/cursos/${courseId}`,
  certificates: '/aluno/certificados',
  downloads: '/aluno/downloads',
  producer: '/produtor',
  producerBeats: '/produtor/beats',
  producerProducts: '/produtor/produtos',
  producerOrders: '/produtor/pedidos',
  premiumLibrary: '/aluno/biblioteca-premium',
  community: '/aluno/comunidade',
  opportunities: '/aluno/oportunidades',
  events: '/aluno/eventos',
  orders: '/aluno/pedidos',
  favorites: '/aluno/favoritos',
  editProfile: '/aluno/perfil',
  settings: '/aluno/configuracoes',
  notifications: '/aluno/notificacoes',
  support: '/aluno/suporte',

  // Instructor area
  instructor: '/instrutor',
  instructorCourses: '/instrutor/cursos',
  instructorAudience: '/instrutor/alunos-avaliacoes',
  instructorReports: '/instrutor/relatorios',
  instructorCourseNew: '/instrutor/cursos/novo',
  instructorCourseEdit: (id: string) => `/instrutor/cursos/${id}`,

  // Admin — /admin/*
  admin: '/admin',
  adminUsers: '/admin/usuarios',
  adminStudents: '/admin/alunos',
  adminSubscriptions: '/admin/assinaturas',
  adminCourses: '/admin/cursos',
  adminCourseNew: '/admin/cursos/novo',
  adminCourseEdit: (id: string) => `/admin/cursos/${id}`,
  adminProducts: '/admin/produtos',
  adminProductNew: '/admin/produtos/novo',
  adminProductEdit: (id: string) => `/admin/produtos/${id}`,
  adminOrders: '/admin/pedidos',
  adminCoupons: '/admin/cupons',
  adminContent: '/admin/conteudos',
  adminEvents: '/admin/eventos',
  adminCertificates: '/admin/certificados',
  adminCommunity: '/admin/comunidade',
  adminReports: '/admin/relatorios',
  adminObservability: '/admin/observabilidade',
  adminSettings: '/admin/configuracoes',
  adminIntegrations: '/admin/integracoes',
  adminFinance: '/admin/financeiro',
  adminMarketing: '/admin/marketing',
  adminSupport: '/admin/suporte',
  adminAudit: '/admin/auditoria',
  adminSecurity: '/admin/seguranca',
} as const;
