export const ROUTES = {
  home: '/',
  login: '/login',
  register: '/matricule-se',
  companyRegister: '/cadastro-empresa',
  forgotPassword: '/esqueceu-senha',
  resetPassword: '/redefinir-senha',
  verifyEmail: '/verificar-email',
  verified: '/verificado',
  comingSoon: '/curso-em-breve',
  accessDenied: '/acesso-negado',
  contact: '/contato',
  privacyPolicy: '/politica-de-privacidade',
  termsOfUse: '/termos-de-uso',
  paymentSuccess: '/pagamento-sucesso',
  validateCertificate: '/validar',

  academy: '/academia',
  academyCourse: (courseSlug: string) => `/academia/${courseSlug}`,
  academyLesson: (courseSlug: string, lessonSlug: string) => `/academia/${courseSlug}/aulas/${lessonSlug}`,
  lesson: (lessonId: string) => `/aula/${lessonId}`,
  marketplace: '/marketplace',
  marketplaceProduct: (productSlug: string) => `/marketplace/${productSlug}`,
  marketplaceBeats: '/marketplace/beats',
  marketplaceBeat: (beatSlug: string) => `/marketplace/beats/${beatSlug}`,
  servicesPublic: '/servicos',
  serviceDetail: (serviceSlug: string) => `/servicos/${serviceSlug}`,
  cart: '/carrinho',
  checkout: '/checkout',

  contentPortal: '/conteudos',
  contentArticle: (articleSlug: string) => `/conteudos/${articleSlug}`,
  communityPublic: '/comunidade',
  opportunitiesPublic: '/oportunidades',

  dashboard: '/aluno',
  myCourses: '/aluno/meus-cursos',
  studentCourse: (courseId: string) => `/aluno/cursos/${courseId}`,
  certificates: '/aluno/certificados',
  downloads: '/aluno/downloads',
  library: '/aluno/biblioteca',
  community: '/aluno/comunidade',
  opportunities: '/aluno/oportunidades',
  studentServices: '/aluno/servicos',
  studentServiceRequests: '/aluno/solicitacoes-servico',
  orders: '/aluno/pedidos',
  favorites: '/aluno/favoritos',
  editProfile: '/aluno/perfil',
  settings: '/aluno/configuracoes',
  notifications: '/aluno/notificacoes',
  support: '/aluno/suporte',

  instructor: '/instrutor',
  instructorCourses: '/instrutor/cursos',
  instructorAudience: '/instrutor/alunos-avaliacoes',
  instructorReports: '/instrutor/relatorios',
  instructorFinance: '/instrutor/financeiro',

  producer: '/produtor',
  producerBeats: '/produtor/beats',
  producerProducts: '/produtor/produtos',
  producerOrders: '/produtor/pedidos',
  producerServices: '/produtor/servicos',
  producerServiceRequests: '/produtor/solicitacoes-servico',

  affiliate: '/afiliado',
  affiliateLinks: '/afiliado/links',
  affiliateConversions: '/afiliado/conversoes',
  affiliateCommissions: '/afiliado/comissoes',
  affiliateWithdrawals: '/afiliado/saques',
  affiliateMaterials: '/afiliado/materiais',
  affiliateProfile: '/afiliado/perfil',

  company: '/empresa',
  companyOpportunities: '/empresa/oportunidades',
  companyCandidates: '/empresa/candidatos',
  companyMessages: '/empresa/mensagens',
  companyProfile: '/empresa/perfil',
  companyCredits: '/empresa/creditos',

  admin: '/admin',
  adminUsers: '/admin/usuarios',
  adminStudents: '/admin/alunos',
  adminCourses: '/admin/cursos',
  adminProducts: '/admin/produtos',
  adminProductNew: '/admin/produtos/novo',
  adminProductEdit: (id: string) => `/admin/produtos/${id}`,
  adminOrders: '/admin/pedidos',
  adminCoupons: '/admin/cupons',
  adminContent: '/admin/conteudos',
  adminCertificates: '/admin/certificados',
  adminCommunity: '/admin/comunidade',
  adminReports: '/admin/relatorios',
  adminObservability: '/admin/observabilidade',
  adminSettings: '/admin/configuracoes',
  adminIntegrations: '/admin/integracoes',
  adminFinance: '/admin/financeiro',
  adminServices: '/admin/servicos',
  adminServiceDisputes: '/admin/servicos/disputas',
  adminMarketing: '/admin/marketing',
  adminSupport: '/admin/suporte',
  adminAudit: '/admin/auditoria',
  adminSecurity: '/admin/seguranca',
} as const;
